#!/bin/bash
# chkconfig: 2345 13 87
# description: Runs ActiveMq


start() {
  /opt/activemq/bin/activemq start
}

stop() {
  /opt/activemq/bin/activemq stop
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage:  {start|stop|restart}"
    exit 1
    ;;
esac
exit $?

